services:
  postgres_dev:
    image: postgres:16.4-bookworm
    restart: always
    env_file:
      - .secrets
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
volumes:
  postgresql_data: